FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu22.04

RUN apt update && apt install git libgl1-mesa-glx libglib2.0-0 unzip wget -y
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b
RUN echo 'cython \n\
kornia==0.5.1 \n\
face-alignment==1.3.5 \n\
ninja==1.10.2.3 \n\
einops==0.4.1 \n\
facexlib==0.2.5 \n\
librosa==0.9.2 \n\
gradio>=3.7.0 \n\
opencv-contrib-python \n\
opencv-python \n\
scikit-image \n\
numpy==1.23' > requirements.txt
RUN /root/miniconda3/bin/conda init bash && /root/miniconda3/bin/conda create -n avatar python=3.8 -y
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "avatar", "/bin/bash", "-c"]
RUN /root/miniconda3/bin/conda env list
RUN wget https://files.pythonhosted.org/packages/86/41/00a6b000f222f0fa4c6d9e1d6dcc9811a374cabb8abb9d408b77de39648c/basicsr-1.4.2.tar.gz
RUN /root/miniconda3/envs/avatar/bin/pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
RUN /root/miniconda3/envs/avatar/bin/pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
RUN /root/miniconda3/envs/avatar/bin/pip install ./basicsr-1.4.2.tar.gz streamlit-image-select -i https://mirrors.aliyun.com/pypi/simple --trusted-host mirrors.aliyun.com
RUN conda install -c conda-forge dlib=19.24 ffmpeg -y

RUN git clone https://github.com/OpenTalker/video-retalking.git
WORKDIR $PWD/video-retalking
RUN sed -i 's/_2D/TWO_D/g' ./third_part/face3d/extract_kp_videos.py && \
sed -i 's/_2D/TWO_D/g' ./utils/alignment_stit.py

RUN mkdir checkpoints
WORKDIR $PWD/video-retalking/checkpoints
RUN echo "https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/30_net_gen.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/BFM.zip \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/DNet.pt \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/ENet.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/expression.mat \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/face3d_pretrain_epoch_20.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/GFPGANv1.3.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/GPEN-BFR-512.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/LNet.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/ParseNet-latest.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/RetinaFace-R50.pth \n\
https://github.com/OpenTalker/video-retalking/releases/download/v0.0.1/shape_predictor_68_face_landmarks.dat" > model_list_urls.txt
RUN wget -i model_list_urls.txt
RUN unzip -d ./BFM BFM.zip

# set conda activate env variable
ENV CONDA_AVATAR_ROOT=/root/miniconda3/envs/avatar/lib CACHE_CHECKPOINTS_ROOT=/root/.cache/torch/hub/checkpoints
RUN wget "https://github.com/xinntao/facexlib/releases/download/v0.1.0/detection_Resnet50_Final.pth"
RUN cp detection_Resnet50_Final.pth ${CONDA_AVATAR_ROOT}/python3.8/site-packages/facexlib/weights/detection_Resnet50_Final.pth
RUN wget "https://github.com/xinntao/facexlib/releases/download/v0.2.2/parsing_parsenet.pth"
RUN cp parsing_parsenet.pth ${CONDA_AVATAR_ROOT}/python3.8/site-packages/facexlib/weights/parsing_parsenet.pth
RUN wget "https://www.adrianbulat.com/downloads/python-fan/s3fd-619a316812.pth"
RUN cp s3fd-619a316812.pth ${CACHE_CHECKPOINTS_ROOT}/s3fd-619a316812.pth
RUN wget "https://www.adrianbulat.com/downloads/python-fan/2DFAN4-cd938726ad.zip"
RUN cp 2DFAN4-cd938726ad.zip ${CACHE_CHECKPOINTS_ROOT}/2DFAN4-cd938726ad.zip

WORKDIR $PWD/video-retalking
#LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${CONDA_AVATAR_ROOT} streamlit run webUI_new.py --server.address 0.0.0.0 --server.port 50330 --server.fileWatcherType none
